import React from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import { Ionicons } from '@expo/vector-icons';
import { colors, spacing } from '@/constants/theme';
import { AssetRecord } from '@/types/submission';
const asset=(uri:string,name:string,mimeType?:string,size?:number):AssetRecord=>({id:`asset-${Date.now()}-${Math.random()}`,uri,name,mimeType,size,selectedAt:new Date().toISOString()});
export function ScreenshotPicker({screenshots,documents,onChangeScreenshots,onChangeDocuments}:{screenshots:AssetRecord[];documents:AssetRecord[];onChangeScreenshots:(items:AssetRecord[])=>void;onChangeDocuments:(items:AssetRecord[])=>void}) {
 const pickImages=async()=>{const p=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!p.granted){Alert.alert('Photo permission needed','Allow photo library access to select local screenshots.');return;} const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,quality:0.9}); if(!r.canceled) onChangeScreenshots([...screenshots,...r.assets.map(a=>asset(a.uri,a.fileName||'Screenshot',a.mimeType,a.fileSize))]);};
 const pickDocs=async()=>{const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:true,type:['application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document']}); if(!r.canceled) onChangeDocuments([...documents,...r.assets.map(a=>asset(a.uri,a.name,a.mimeType,a.size))]);};
 return <View><Pressable style={styles.button} onPress={pickImages}><Ionicons name="images-outline" size={20} color={colors.white}/><Text style={styles.buttonText}>Select screenshots</Text></Pressable>{screenshots.length>0&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.gallery}>{screenshots.map((a,i)=><View key={a.id} style={styles.thumbWrap}><Image source={{uri:a.uri}} style={styles.thumb}/><Pressable accessibilityLabel={`Remove screenshot ${i+1}`} onPress={()=>onChangeScreenshots(screenshots.filter(x=>x.id!==a.id))} style={styles.remove}><Ionicons name="close" size={16} color={colors.white}/></Pressable></View>)}</ScrollView>}
 <Text style={styles.subhead}>Supporting documents</Text><Pressable style={[styles.button,styles.secondary]} onPress={pickDocs}><Ionicons name="document-attach-outline" size={20} color={colors.text}/><Text style={[styles.buttonText,{color:colors.text}]}>Select documents</Text></Pressable>{documents.map(a=><View key={a.id} style={styles.document}><Ionicons name="document-text-outline" size={20} color={colors.blue}/><Text numberOfLines={1} style={styles.documentName}>{a.name}</Text><Pressable accessibilityLabel={`Remove ${a.name}`} onPress={()=>onChangeDocuments(documents.filter(x=>x.id!==a.id))}><Ionicons name="close-circle" size={22} color={colors.muted}/></Pressable></View>)}</View>;
}
const styles=StyleSheet.create({button:{backgroundColor:colors.blue,borderRadius:10,padding:12,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8},secondary:{backgroundColor:colors.navy,borderWidth:1,borderColor:colors.line},buttonText:{color:colors.white,fontWeight:'700'},gallery:{gap:12,paddingVertical:14},thumbWrap:{position:'relative'},thumb:{width:112,height:190,borderRadius:12,backgroundColor:colors.navy},remove:{position:'absolute',top:5,right:5,backgroundColor:colors.coral,borderRadius:13,padding:2},subhead:{color:colors.muted,fontWeight:'700',fontSize:12,textTransform:'uppercase',marginTop:8,marginBottom:8},document:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},documentName:{color:colors.text,flex:1}});
